# Use root/example as user/password credentials
version: '3.1'

services:

    db:
        image: mysql
        command: --default-authentication-plugin=mysql_native_password
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: example
        volumes:
          - ./mysql:/var/lib/mysql
        ports:
          - 3316:3306

    adminer:
        image: adminer
        restart: always
        ports:
            - "8081:8080"

    backend:
        build:
            dockerfile: Dockerfile-backend
            context: .
        restart: always
        environment:
          NODE_ENV: ${NODE_ENV}
        volumes:
          - .:/usr/src/app/
        ports:
          - "8080:82"
          - "2000:2000"
        depends_on:
          - db

    migrations:
        build:
          dockerfile: Dockerfile-migrations
          context: .
        environment:
          NODE_ENV: ${NODE_ENV}
        volumes:
          - .:/usr/src/app/
        command: bash -c "node create_database.js && knex migrate:latest --env ${NODE_ENV} migrate"
        depends_on:
          - db

    gulp:
        build:
            dockerfile: Dockerfile-gulp
            context: .
        volumes:
            - .:/usr/src/app/
        command: gulp

    webpack:
        restart: unless-stopped
        build:
            dockerfile: Dockerfile-webpack
            context: .
        environment:
            NODE_ENV: ${NODE_ENV}
        volumes:
            - .:/usr/src/app/
        command: npm run build
        ports:
            - 9000:9000