FROM node:12

RUN mkdir /usr/src/app
RUN chmod -R 777 /usr/src/app

COPY . /usr/src/app

WORKDIR /usr/src/app

RUN npm install -g nodemon knex
RUN npm install
RUN apt-get update \
  && apt-get install -y netcat net-tools python-pip

RUN pip install trueskill sqlalchemy mysql-python

CMD ["nodemon", "server"]