#FROM hypriot/wiringpi or hypriot/rpi-gpio but both without Dockerfile and probably ARM-only

RUN apt-get update && \
  apt-get install -y git vim sudo

RUN git clone https://github.com/WiringPi/WiringPi.git && \
  cd WiringPi && \
  chmod u+x build && \
  ./build

ARG LDFLAGS=-lpthread

RUN git clone --recursive https://github.com/ninjablocks/433Utils.git && \
  cd 433Utils/RPi_utils && \

  add "-lpthread" to all targets; make

CMD ["nodemon", "server"]

RUN apk update && apk upgrade && \
    apk add --no-cache bash git openssh